### ISSUE TITLE
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

### ISSUE THREAD

**Issue by birdjumper** [nimia/public_drown_scanner#38]
Hi

When I run 'python scanner.py localhost 443' I get:

Traceback (most recent call last):
  File "scanner.py", line 25, in <module>
    from ssl_tls import *
  File "/home/ian/public_drown_scanner-master/scapy-ssl_tls/ssl_tls.py", line 11, in <module>
    from scapy_ssl_tls import ssl_tls_crypto
  File "/usr/lib/python2.6/site-packages/scapy_ssl_tls/ssl_tls_crypto.py", line 19, in <module>
    from Crypto.Cipher import AES, ARC2, ARC4, DES, DES3, PKCS1_v1_5
  File "/usr/lib64/python2.6/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 73, in <module>
    from Crypto.Util.number import ceil_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'

OS is Red Hat Enterprise Linux Server release 6.7 (Santiago)

Any ideas?

Thanks

**Comment by nimia** [comment]
Thanks for your report. The only idea that comes to mind is maybe this:
https://github.com/nimia/public_drown_scanner/issues/30#issuecomment-191492816

hope this works out, best,
Nimrod

**Comment by birdjumper** [comment]
it did thanks
