### ISSUE TITLE
Not Working On Windows

### ISSUE THREAD

**Issue by LeeThompson** [nimia/public_drown_scanner#44]
This may be an issue with setup but:

```
Traceback (most recent call last):
  File "scanner.py", line 22, in <module> from scapy.all import *
  File "C:\python\lib\site-packages\scapy\all.py", line 16, in <module> from arch import *
  File "C:\python\lib\site-packages\scapy\arch\__init__.py", line 80, in <module> from windows import *
  File "C:\python\lib\site-packages\scapy\arch\windows\__init__.py", line 23, in <module> from scapy.arch import pcapdnet
  File "C:\python\lib\site-packages\scapy\arch\pcapdnet.py", line 30, in <module> import pcapy as pcap
ImportError: No module named pcapy
```

Windows 7 SP1
Python 2.7.11 + pycrypto

The required dependencies should all be there:

```
> pip install enum pycrypto scapy pyasn1 scapy-ssl_tls

Requirement already satisfied (use --upgrade to upgrade): enum in c:\python\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pycrypto in c:\python\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): scapy in c:\python\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in c:\python\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): scapy-ssl-tls in c:\python\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python\lib\site-packages (from enum)
Requirement already satisfied (use --upgrade to upgrade): tinyec in c:\python\lib\site-packages (from scapy-ssl-tls)
```

**Comment by nimia** [comment]
Does running
`pip install pcapy`
solve the problem?

best,
Nimrod

**Comment by tintinweb** [comment]
scapy and py2.7 has some known issues on windows 
see [scapy documentation#windows](http://www.secdev.org/projects/scapy/doc/installation.html#windows) which recommends running py2.6
and [this stackoverflow answer](https://stackoverflow.com/questions/5447461/running-scapy-on-windows-with-python-2-7) on how to make it work with py2.7 (be careful with precompiled libs from untrusted sources)

**Comment by nimia** [comment]
@tintinweb, you rock! :-)
