### ISSUE TITLE
centos issue

### ISSUE THREAD

**Issue by AxisNL** [nimia/public_drown_scanner#45]
I installed all the dependencies as listed. When running, I get the following error. Any ideas?

```
[angelo@scanner public_drown_scanner]$ ./scanner.py www.google.com 443
Traceback (most recent call last):
  File "./scanner.py", line 25, in <module>
    from pyx509.pkcs7.asn1_models.X509_certificate import Certificate
  File "/home/angelo/drown/public_drown_scanner/pyx509/pkcs7/asn1_models/X509_certificate.py", line 32, in <module>
    from tools import *
  File "/home/angelo/drown/public_drown_scanner/pyx509/pkcs7/asn1_models/tools.py", line 24, in <module>
    from decoder_workarounds import decode
  File "/home/angelo/drown/public_drown_scanner/pyx509/pkcs7/asn1_models/decoder_workarounds.py", line 10, in <module>
    class BooleanFixDerDecoder(derDecoder.Decoder): pass
AttributeError: 'module' object has no attribute 'Decoder'
```

```
[angelo@scanner public_drown_scanner]$ cat /etc/redhat-release 
CentOS release 6.7 (Final)
[angelo@scanner public_drown_scanner]$ name -a
Linux scanner.netmatch.nl 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nimia** [comment]
Have you tried https://github.com/nimia/public_drown_scanner/issues/30?

best,
Nimrod
