### ISSUE TITLE
Cannot import `PKCS1_v1_5`

### ISSUE THREAD

**Issue by BRMatt** [nimia/public_drown_scanner#5]
Running on ubuntu 12.04, using the system version of python:

``` console
$ python scanner.py google.com 443     
Import Error - most likely due to missing pycrypto libraries - disabling crypto functionality
ImportError('cannot import name PKCS1_v1_5',)
Traceback (most recent call last):
  File "scanner.py", line 20, in <module>
    import ssl_tls_crypto
  File "./scapy-ssl_tls/ssl_tls_crypto.py", line 13, in <module>
    from Crypto.Cipher import PKCS1_v1_5#,PKCS1_OAEP
ImportError: cannot import name PKCS1_v1_5
```

Installed python packages:

``` console
$ sudo dpkg -l | grep python
ii  libpython2.7                     2.7.3-0ubuntu3.8                                   Shared Python runtime library (version 2.7)
ii  libpython3.2                     3.2.3-0ubuntu3.7                                   Shared Python runtime library (version 3.2)
ii  python                           2.7.3-0ubuntu2.2                                   interactive high-level object-oriented language (default version)
ii  python-apt                       0.8.3ubuntu7.3                                     Python interface to libapt-pkg
ii  python-apt-common                0.8.3ubuntu7.3                                     Python interface to libapt-pkg (locales)
ii  python-chardet                   2.0.1-2build1                                      universal character encoding detector
ii  python-crypto                    2.4.1-1ubuntu0.1                                   cryptographic algorithms and protocols for Python
ii  python-dbg                       2.7.3-0ubuntu2.2                                   debug build of the Python Interpreter (version 2.7)
ii  python-dbus                      1.0.0-1ubuntu1                                     simple interprocess messaging system (Python interface)
ii  python-dbus-dev                  1.0.0-1ubuntu1                                     main loop integration development files for python-dbus
ii  python-debian                    0.1.21ubuntu1                                      Python modules to work with Debian-related data formats
ii  python-dev                       2.7.3-0ubuntu2.2                                   header files and a static library for Python (default)
ii  python-enum                      0.4.4-2                                            robust enumerated type support in Python
ii  python-gdbm                      2.7.3-1ubuntu1                                     GNU dbm database support for Python
ii  python-gi                        3.2.2-1~precise                                    Python 2.x bindings for gobject-introspection libraries
ii  python-gnupginterface            0.3.2-9.1ubuntu3                                   Python interface to GnuPG (GPG)
ii  python-impacket                  0.9.6.0-3                                          Python module to easily build and dissect network protocols
ii  python-minimal                   2.7.3-0ubuntu2.2                                   minimal subset of the Python language (default version)
ii  python-pcapy                     0.10.8-1build1                                     Python interface to the libpcap packet capture library
ii  python-pip                       1.0-1build1                                        alternative Python package installer
ii  python-pkg-resources             0.6.24-1ubuntu1                                    Package Discovery and Resource Access using pkg_resources
ii  python-pyasn1                    0.0.11a-1ubuntu1                                   ASN.1 library for Python
ii  python-pycryptopp                0.5.29-1build1                                     Python wrappers for the Crypto++ library
ii  python-pycryptopp-dbg            0.5.29-1build1                                     Python wrappers for the Crypto++ library (debug extension)
ii  python-pycurl                    7.19.0-4ubuntu3                                    Python bindings to libcurl
ii  python-scapy                     2.2.0-1                                            Packet generator/sniffer and network scanner/discovery
ii  python-setuptools                0.6.24-1ubuntu1                                    Python Distutils Enhancements (setuptools compatibility)
ii  python-software-properties       0.82.7.7                                           manage the repositories that you install software from
ii  python-support                   1.0.14ubuntu2                                      automated rebuilding support for Python modules
ii  python-xapian                    1.2.8-1                                            Xapian search engine interface for Python
ii  python2.7                        2.7.3-0ubuntu3.8                                   Interactive high-level object-oriented language (version 2.7)
ii  python2.7-dbg                    2.7.3-0ubuntu3.8                                   Debug Build of the Python Interpreter (version 2.7)
ii  python2.7-dev                    2.7.3-0ubuntu3.8                                   Header files and a static library for Python (v2.7)
ii  python2.7-minimal                2.7.3-0ubuntu3.8                                   Minimal subset of the Python language (version 2.7)
```

Am I missing a required crypto library?

**Comment by nimia** [comment]
I have a more recent pycrypto package, 2.6.1-4build1, perhaps this is the issue?

**Comment by BRMatt** [comment]
Could be, though the version you quoted doesn't seem to be available for precise. I tried setting up a virtualenv to avoid using the system package, but it still doesn't seem to work: 

```
(foo)/t/public_drown_scanner git:master ❯❯❯ python --version
Python 2.7.3
(foo)/t/public_drown_scanner git:master ❯❯❯ pip freeze  
Naked==0.1.31
PyYAML==3.11
argparse==1.2.1
crypto==1.4.1
distribute==0.6.24
enum==0.4.6
requests==2.9.1
shellescape==3.4.1
wsgiref==0.1.2
(foo)/t/public_drown_scanner git:master ❯❯❯ python scanner.py google.com 443 
Traceback (most recent call last):
  File "scanner.py", line 8, in <module>
    import Crypto.Cipher
ImportError: No module named Crypto.Cipher
```

Don't suppose anything else seems obviously wrong?

**Comment by BRMatt** [comment]
Discovered a few packages were missing, this now works in a virtualenv:

``` console
$ pip freeze 
Naked==0.1.31
PyYAML==3.11
argparse==1.2.1
crypto==1.4.1
distribute==0.6.24
enum==0.4.6
pyasn1==0.1.9
pycrypto==2.6.1
requests==2.9.1
scapy==2.3.2
shellescape==3.4.1
wsgiref==0.1.2
$ python scanner.py google.com 443
Import Error - most likely due to missing pycrypto libraries - disabling crypto functionality
ImportError('cannot import name TLSHandshake',)
Testing google.com on port 443
google.com: Case 3d; Server hello did not contain server hello
google.com: Server is NOT vulnerable with cipher RC2_128_CBC_EXPORT40_WITH_MD5, Message: 3d: no tls

google.com: Case 3d; Server hello did not contain server hello
google.com: Server is NOT vulnerable with cipher RC4_128_EXPORT40_WITH_MD5, Message: 3d: no tls

google.com: Case 3d; Server hello did not contain server hello
google.com: Server is NOT vulnerable with cipher RC4_128_WITH_MD5, Message: 3d: no tls

google.com: Case 3d; Server hello did not contain server hello
google.com: Server is NOT vulnerable with cipher DES_64_CBC_WITH_MD5, Message: 3d: no tls
```

**Comment by Ezerbeth** [comment]
Same problem on FreeBSD... 
ImportError('cannot import name TLSHandshake',)

And on OSX, it brings LLVM as dependency... eek.

**Comment by nimia** [comment]
> ImportError('cannot import name TLSHandshake',)
> That's not a problem actually, if you still see the results then it's fine.
> I realize this message confuses people, and am working on removing it.
